# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UR7poaGOtYtlupOKZvb3CW0X3cXIjAIc
"""

amount = int(input("Enter purchase amount: "))
if amount > 0:
    print("Valid Purchase")
else:
    print("Invalid Purchase")