# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mNsjSvu-kV2tmmjb2rcu2aEqPbrQSISZ
"""

distance = float(input("Enter delivery distance (in km): "))
if distance <= 5:
    print("Delivery Category: Local")
elif distance > 5 and distance <= 20:
    print("Delivery Category: City")
else:
    print("Delivery Category: Outstation")