# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4M7TXYUvJ-FFyEhFnTQcFFm7ZUq6VEQ
"""

feedback = {}
n = int(input("Enter number of feedback types: "))
for i in range(n):
    type = input("Enter feedback type: ")
    count = int(input("Enter feedback count: "))
    feedback[type] = count
total = 0
for value in feedback.values():
    total = total + value
type = ""
count = 0
for key, value in feedback.items():
    if value > count:
        count = value
        type = key
print("\nTotal Feedback:", total)
print("Highest Feedback Type:", type)
print("Feedback Count:", count)