# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UR7poaGOtYtlupOKZvb3CW0X3cXIjAIc
"""

products = []
opening_stock = []
closing_stock = []
n = int(input("Enter number of products: "))
for i in range(n):
    name = input(f"\nEnter product {i+1} name: ")
    products.append(name)
    open_stock = int(input(f"Enter opening stock for {name}: "))
    opening_stock.append(open_stock)
    close_stock = int(input(f"Enter closing stock for {name}: "))
    closing_stock.append(close_stock)
print("Stock Comparison Report")
for i in range(n):
    if closing_stock[i] > opening_stock[i]:
        print(products[i], "stock increased")
    elif closing_stock[i] < opening_stock[i]:
        print(products[i], "stock decreased")
    else:
        print(products[i], "stock unchanged")