# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4M7TXYUvJ-FFyEhFnTQcFFm7ZUq6VEQ
"""

scores = []
n = int(input("Enter number of students: "))
for i in range(n):
    score = float(input("Enter score: "))
    scores.append(score)
total = sum(scores)
average = total / n
count = 0
for s in scores:
    if s > average:
        count += 1
print("\nTotal Score:", total)
print("Average Score:", average)
print("Scores above average:", count)