# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4M7TXYUvJ-FFyEhFnTQcFFm7ZUq6VEQ
"""

prices = (499.99, 1299.50, 299.00, 799.25)
print("First product price:", prices[0])
print("Second product price:", prices[1])
print("Product prices:", prices)