# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sM8kiWcBmjWLn6GV1pVIYTjPaft6xFcX
"""

n = int(input("Enter number of products: "))
products = {}
for i in range(n):
    name = input(f"Enter product {i+1} name: ")
    category = input(f"Enter category for {name}: ")
    products[name] = category
print("\nProduct Names:")
for product in products.keys():
    print(product)
print("\nCategories:")
for category in products.values():
    print(category)
print("\nTotal Products:", len(products))