# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z4M7TXYUvJ-FFyEhFnTQcFFm7ZUq6VEQ
"""

students = {
    "Ashok": "Java",
    "Chetan": "Data Analytics",
    "Maning": "AI",
    "sachin": "HTML"
}
print("Student Names:")
for name in students.keys():
    print(name)
print("\nEnrolled Courses:")
for course in students.values():
    print(course)
    student = input("\nEnter student name to check: ")
if student in students:
    print(student, "is enrolled in", students[student])
else:
    print(student, "does not exist in the records")