# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UR7poaGOtYtlupOKZvb3CW0X3cXIjAIc
"""

visitors = []
for i in range(7):
    count = int(input(f"Enter visitors for day {i+1}: "))
    visitors.append(count)
highest_traffic = max(visitors)
lowest_traffic = min(visitors)
print("Highest Traffic:", highest_traffic)
print("Lowest Traffic:", lowest_traffic)